/*** Generated by streamline 0.6.0 (callbacks) - DO NOT EDIT ***/ var __rt=require('streamline/lib/callbacks/runtime').runtime(__filename),__func=__rt.__func,__cb=__rt.__cb; (function() {
  var Connection, ConnectionValidator, NodeType, NodeWrapper, __hasProp = {
  }.hasOwnProperty, __extends = function(child, parent) {
    for (var key in parent) { if (__hasProp.call(parent, key)) { child[key] = parent[key]; }; }; function ctor() { this.constructor = child; }; ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  NodeWrapper = require("./NodeWrapper");

  NodeType = require("./NodeType");

  ConnectionValidator = require("./validation/connectionValidator");

  module.exports = Connection = (function(_super) {
    __extends(Connection, _super);






    Connection.getNodeType = function() {
      return NodeType.CONNECTION; };


    Connection.wrap = function(node) {
      return new Connection(node); };


    Connection.create = function Connection_create__1(data, creator, _) { var created, __this = this; var __frame = { name: "Connection_create__1", line: 28 }; return __func(_, this, arguments, Connection_create__1, 2, __frame, function __$Connection_create__1() {

        data.active = true;
        return Connection.__super__.constructor.create.call(__this, data, __cb(_, __frame, 3, 16, function ___(__0, __1) { created = __1;
          return creator.setAsCreator(created, __cb(_, __frame, 4, 6, function __$Connection_create__1() {
            return _(null, created); }, true)); }, true)); }); };


    Connection.connect = function Connection_connect__2(startResource, endResource, user, data, _) { var connection, relationshipData, __this = this; var __frame = { name: "Connection_connect__2", line: 36 }; return __func(_, this, arguments, Connection_connect__2, 4, __frame, function __$Connection_connect__2() {

        relationshipData = {
          creationDate: new Date() };

        return __this.create(data, user, __cb(_, __frame, 5, 19, function ___(__0, __1) { connection = __1;
          return startResource.node.createRelationshipTo(connection.node, "RELATED_TO", relationshipData, __cb(_, __frame, 6, 6, function __$Connection_connect__2() {
            return connection.node.createRelationshipTo(endResource.node, "RELATED_TO", relationshipData, __cb(_, __frame, 7, 6, function __$Connection_connect__2() {
              return _(null, connection); }, true)); }, true)); }, true)); }); };







    function Connection(node) {
      Connection.__super__.constructor.call(this, node); };


    Connection.prototype.validate = function() {
      return new ConnectionValidator().validate(this.node.data); };


    return Connection;

  })(NodeWrapper);

}).call(this);