/*** Generated by streamline 0.6.0 (callbacks) - DO NOT EDIT ***/ var __rt=require('streamline/lib/callbacks/runtime').runtime(__filename),__func=__rt.__func,__cb=__rt.__cb; (function() {
  var DBConf, Error, Neo4j, NodeWrapper;

  Neo4j = require("neo4j");

  DBConf = require("../config/DB.conf");

  Error = require("../error/Error");

  module.exports = NodeWrapper = (function() {




    NodeWrapper.DB = new Neo4j.GraphDatabase(DBConf.getDBURL("neo4j"));

    NodeWrapper.getNodeType = function() {
      throw Error.notImplemented("NodeWrapper.getNodeType()"); };


    NodeWrapper.getValidator = function() {
      throw Error.notImplemented("NodeWrapper.getValidator()"); };


    NodeWrapper.wrap = function(node) {
      throw Error.notImplemented("NodeWrapper.wrap()"); };


    NodeWrapper.create = function NodeWrapper_create__1(data, _) { var created, __this = this; var __frame = { name: "NodeWrapper_create__1", line: 29 }; return __func(_, this, arguments, NodeWrapper_create__1, 1, __frame, function __$NodeWrapper_create__1() {

        data.KN_ID = __this.GUID();
        data.nodeType = __this.getNodeType();
        data.__CreatedOn__ = Date.now();
        created = __this.wrap(__this.DB.createNode(data));
        return created.save(__cb(_, __frame, 6, 6, function __$NodeWrapper_create__1() {
          return _(null, created); }, true)); }); };


    NodeWrapper.find = function NodeWrapper_find__2(id, _) { var __this = this; var __frame = { name: "NodeWrapper_find__2", line: 39 }; return __func(_, this, arguments, NodeWrapper_find__2, 1, __frame, function __$NodeWrapper_find__2() {
        return __this.findNodeById(id, __cb(_, __frame, 1, 23, function ___(__0, __2) { var __1 = __this.wrap(__2); return _(null, __1); }, true)); }); };


    NodeWrapper.findNodeById = function NodeWrapper_findNodeById__3(id, _) { var node, __this = this; var __frame = { name: "NodeWrapper_findNodeById__3", line: 43 }; return __func(_, this, arguments, NodeWrapper_findNodeById__3, 1, __frame, function __$NodeWrapper_findNodeById__3() {

        return __this.DB.getIndexedNode(__this.getNodeType(), "KN_ID", id, __cb(_, __frame, 2, 13, function ___(__0, __1) { node = __1;
          if ((node == null)) {
            return _(Error.entityNotFound(__this.getNodeType(), id)); }
           else {
            return _(null, node); } ; _(); }, true)); }); };



    NodeWrapper.GUID = function() {
      return "xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g, function(c) {
        var r, v;
        r = ((Math.random() * 16) | 0);
        v = (((c === "x") ? r : ((r & 3) | 8)));
        return v.toString(16); }); };








    function NodeWrapper(node) {
      this.node = node;
      if ((this.node == null)) {
        throw Error.illegalArgument(this.node, "NodeWrapper.constructor()"); } ; };



    NodeWrapper.prototype.getId = function() {
      return this.node.data["KN_ID"]; };


    NodeWrapper.prototype.save = function NodeWrapper_prototype_save__4(_) { var __this = this; var __frame = { name: "NodeWrapper_prototype_save__4", line: 78 }; return __func(_, this, arguments, NodeWrapper_prototype_save__4, 0, __frame, function __$NodeWrapper_prototype_save__4() {
        __this.validate();
        return __this.node.save(__cb(_, __frame, 2, 6, function __$NodeWrapper_prototype_save__4() {
          return __this.index(__cb(_, __frame, 3, 6, function __$NodeWrapper_prototype_save__4() { return _(null, __this); }, true)); }, true)); }); };



    NodeWrapper.prototype.update = function NodeWrapper_prototype_update__5(newData, _) { var oldData, __this = this; var __frame = { name: "NodeWrapper_prototype_update__5", line: 85 }; return __func(_, this, arguments, NodeWrapper_prototype_update__5, 1, __frame, function __$NodeWrapper_prototype_update__5() {

        oldData = __this.node._data.data;
        newData.__CreatedOn__ = oldData.__CreatedOn__;
        __this.node._data.data = newData;
        return __this.save(__cb(_, __frame, 5, 6, function __$NodeWrapper_prototype_update__5() { return _(null, __this); }, true)); }); };



    NodeWrapper.prototype["delete"] = function NodeWrapper_prototype_delete__6(_) { var __this = this; var __frame = { name: "NodeWrapper_prototype_delete__6", line: 94 }; return __func(_, this, arguments, NodeWrapper_prototype_delete__6, 0, __frame, function __$NodeWrapper_prototype_delete__6() {
        return __this.node["delete"](__cb(_, __frame, 1, 13, _, true)); }); };


    NodeWrapper.prototype.index = function NodeWrapper_prototype_index__7(_) { var __this = this; var __frame = { name: "NodeWrapper_prototype_index__7", line: 98 }; return __func(_, this, arguments, NodeWrapper_prototype_index__7, 0, __frame, function __$NodeWrapper_prototype_index__7() {
        return __this.indexProperty("KN_ID", __cb(_, __frame, 1, 13, _, true)); }); };


    NodeWrapper.prototype.indexProperty = function NodeWrapper_prototype_indexProperty__8(key, _) { var __this = this; var __frame = { name: "NodeWrapper_prototype_indexProperty__8", line: 102 }; return __func(_, this, arguments, NodeWrapper_prototype_indexProperty__8, 1, __frame, function __$NodeWrapper_prototype_indexProperty__8() {
        return __this.node.index(__this.node.data["nodeType"], key, __this.node.data[key], __cb(_, __frame, 1, 13, _, true)); }); };


    NodeWrapper.prototype.indexTextProperty = function NodeWrapper_prototype_indexTextProperty__9(key, _) { var __this = this; var __frame = { name: "NodeWrapper_prototype_indexTextProperty__9", line: 106 }; return __func(_, this, arguments, NodeWrapper_prototype_indexTextProperty__9, 1, __frame, function __$NodeWrapper_prototype_indexTextProperty__9() {
        return __this.node.index(__this.node.data["nodeType"], key, __this.node.data[key].toLowerCase(), __cb(_, __frame, 1, 13, _, true)); }); };







    NodeWrapper.prototype.validate = function() {
      throw Error.notImplemented("NodeWrapper.getValidator()"); };


    return NodeWrapper;

  })();

}).call(this);