// Generated by CoffeeScript 1.6.1
(function() {
  var NodeType;

  module.exports = NodeType = (function() {

    function NodeType() {}

    NodeType.RESOURCE = 'kn_Post';

    NodeType.CONNECTION = 'kn_Edge';

    NodeType.USER = 'kn_User';

    return NodeType;

  })();

}).call(this);
