/*** Generated by streamline 0.6.0 (callbacks) - DO NOT EDIT ***/ var __rt=require('streamline/lib/callbacks/runtime').runtime(__filename),__func=__rt.__func,__cb=__rt.__cb; (function() {
  var Connection, Error, NodeType, NodeWrapper, Resource, ResourceValidator, __hasProp = {
  }.hasOwnProperty, __extends = function(child, parent) {
    for (var key in parent) { if (__hasProp.call(parent, key)) { child[key] = parent[key]; }; }; function ctor() { this.constructor = child; }; ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  NodeWrapper = require("./NodeWrapper");

  NodeType = require("./NodeType");

  ResourceValidator = require("./validation/resourceValidator");

  Connection = require("./Connection");

  Error = require("../error/Error");

  module.exports = Resource = (function(_super) {
    __extends(Resource, _super);

    Resource.Type = {
      WIKIPEDIA_ARTICLE: "Wikipedia Article" };







    Resource.getNodeType = function() {
      return NodeType.RESOURCE; };


    Resource.wrap = function(node) {
      return new Resource(node); };


    Resource.create = function Resource_create__1(data, creator, _) { var created, __this = this; var __frame = { name: "Resource_create__1", line: 36 }; return __func(_, this, arguments, Resource_create__1, 2, __frame, function __$Resource_create__1() {

        data.active = true;
        return Resource.__super__.constructor.create.call(__this, data, __cb(_, __frame, 3, 16, function ___(__0, __1) { created = __1;
          return creator.setAsCreator(created, __cb(_, __frame, 4, 6, function __$Resource_create__1() {
            return _(null, created); }, true)); }, true)); }); };


    Resource.searchByKeyword = function Resource_searchByKeyword__2(userQuery, _) { var cypherQuery, nodes, params, regex, __this = this; var __frame = { name: "Resource_searchByKeyword__2", line: 44 }; return __func(_, this, arguments, Resource_searchByKeyword__2, 1, __frame, function __$Resource_searchByKeyword__2() {

        nodes = [];
        cypherQuery = ["START results=node(*)","Where has(results.title)","and results.nodeType=\"kn_Post\"","and results.title =~ {regex}","RETURN results",].join("\n");
        regex = (("(?i).*" + userQuery) + ".*");
        params = {
          regex: regex };

        return __this.DB.query(cypherQuery, params, __cb(_, __frame, 8, 6, function ___(__0, __2) { return __2.map_(__cb(_, __frame, 8, 6, function __$Resource_searchByKeyword__2() {



            return _(null, nodes); }, true), function __1(_, item) { var __frame = { name: "__1", line: 52 }; return __func(_, this, arguments, __1, 0, __frame, function __$__1() { item.results.data.id = item.results.id; return _(null, nodes.push(item.results.data)); }); }); }, true)); }); };


    Resource.findByUrl = function Resource_findByUrl__3(url, _) { var node, __this = this; var __frame = { name: "Resource_findByUrl__3", line: 59 }; return __func(_, this, arguments, Resource_findByUrl__3, 1, __frame, function __$Resource_findByUrl__3() {

        return __this.DB.getIndexedNode(__this.getNodeType(), "url", url, __cb(_, __frame, 2, 13, function ___(__0, __1) { node = __1;
          if ((node == null)) {
            return _(Error.entityNotFound(__this.getNodeType(), "url", url)); }
           else {
            return _(null, __this.wrap(node)); } ; _(); }, true)); }); };








    function Resource(node) {
      Resource.__super__.constructor.call(this, node); };


    Resource.prototype.connectTo = function Resource_prototype_connectTo__4(other, user, data, _) { var __this = this; var __frame = { name: "Resource_prototype_connectTo__4", line: 78 }; return __func(_, this, arguments, Resource_prototype_connectTo__4, 3, __frame, function __$Resource_prototype_connectTo__4() {
        return Connection.connect(__this, other, user, data, __cb(_, __frame, 1, 13, _, true)); }); };


    Resource.prototype.validate = function() {
      return new ResourceValidator().validate(this.node.data); };


    Resource.prototype.index = function Resource_prototype_index__5(_) { var __this = this; var __frame = { name: "Resource_prototype_index__5", line: 86 }; return __func(_, this, arguments, Resource_prototype_index__5, 0, __frame, function __$Resource_prototype_index__5() {
        return Resource.__super__.index.call(__this, __cb(_, __frame, 1, 6, function __$Resource_prototype_index__5() { return (function __$Resource_prototype_index__5(__then) {
            if ((__this.node.data["url"] != null)) {
              return __this.indexTextProperty("url", __cb(_, __frame, 3, 15, _, true)); } else { __then(); } ; })(_); }, true)); }); };



    return Resource;

  })(NodeWrapper);

}).call(this);