/*** Generated by streamline 0.6.0 (callbacks) - DO NOT EDIT ***/ var __rt=require('streamline/lib/callbacks/runtime').runtime(__filename),__func=__rt.__func,__cb=__rt.__cb; (function() {
  var NodeType, NodeWrapper, User, UserValidator, cache, __hasProp = {
  }.hasOwnProperty, __extends = function(child, parent) {
    for (var key in parent) { if (__hasProp.call(parent, key)) { child[key] = parent[key]; }; }; function ctor() { this.constructor = child; }; ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  NodeWrapper = require("./NodeWrapper");

  NodeType = require("./NodeType");

  UserValidator = require("./validation/userValidator");

  cache = require("memory-cache");

  module.exports = User = (function(_super) {
    __extends(User, _super);

    User.VALIDATOR = new UserValidator;






    User.getNodeType = function() {
      return NodeType.USER; };


    User.wrap = function(node) {
      return new User(node); };


    User.findById = function User_findById__1(id, _) { var db, user, userNode, __this = this; var __frame = { name: "User_findById__1", line: 32 }; return __func(_, this, arguments, User_findById__1, 1, __frame, function __$User_findById__1() {

        user = cache.get(("USER_" + id)); return (function __$User_findById__1(__then) {
          if ((user == null)) {
            db = __this.getDB();
            return db.getIndexedNode("kn_User", "KN_ID", id, __cb(_, __frame, 5, 19, function ___(__0, __1) { userNode = __1;
              user = new User(userNode);
              cache.put(("USER_" + user.getId()), user, 1000); __then(); }, true)); } else { __then(); } ; })(function __$User_findById__1() {

          return _(null, user); }); }); };







    function User(node) {
      User.__super__.constructor.call(this, node); };


    User.prototype.isLoggedIn = function() {
      return (this.node != null); };


    User.prototype.setAsCreator = function User_prototype_setAsCreator__2(created, _) { var properties, __this = this; var __frame = { name: "User_prototype_setAsCreator__2", line: 57 }; return __func(_, this, arguments, User_prototype_setAsCreator__2, 1, __frame, function __$User_prototype_setAsCreator__2() {

        properties = {
          creationDate: new Date() };

        return __this.node.createRelationshipTo(created.node, "CREATED_BY", properties, __cb(_, __frame, 5, 13, _, true)); }); };


    User.prototype.validate = function() {
      return new UserValidator().validate(this.node.data); };


    User.prototype.save = function User_prototype_save__3(_) { var __this = this; var __frame = { name: "User_prototype_save__3", line: 69 }; return __func(_, this, arguments, User_prototype_save__3, 0, __frame, function __$User_prototype_save__3() {
        return User.__super__.save.call(__this, __cb(_, __frame, 1, 6, function __$User_prototype_save__3() {
          return _(null, cache.put(("USER_" + __this.getId()), __this, 1000)); }, true)); }); };


    return User;

  })(NodeWrapper);

}).call(this);