// Generated by CoffeeScript 1.4.0

/*
* This is the routing for the comments on edges / knownodes
*/


(function() {
  var baseController, commentModule;

  commentModule = require('../../modules/comment');

  baseController = require('../baseController');

  module.exports = {
    options: {
      before: {
        index: [baseController.isAdmin()],
        destroy: [baseController.isAdmin]
      }
    },
    index: function(request, response) {
      var cb;
      cb = baseController.callBack(response);
      return commentModule.getAllComments(request.params.knownode, cb);
    },
    create: function(request, response) {
      var cb;
      cb = baseController.callBack(response);
      return commentModule.createNewComment(request.body.comment, request.params.knownode, cb);
    }
  };

}).call(this);
