// Generated by CoffeeScript 1.6.1

/*
* This is the routing for the users. It calls /modules/user.js for implementing its actions.
*/


(function() {
  var baseController, user, userModule;

  userModule = require('../../modules/user');

  baseController = require('../baseController');

  user = new userModule;

  module.exports = {
    options: {
      before: {
        index: [baseController.isAdmin],
        destroy: [baseController.isAdmin]
      }
    },
    index: function(request, response) {
      var cb;
      cb = baseController.callBack(response);
      return user.getAllUsers(cb);
    },
    show: function(request, response) {
      var cb, id;
      cb = baseController.callBack(response);
      id = request.params.user.replace(/:/g, '');
      return user.getUserByNodeId(id, cb);
    },
    create: function(request, response) {
      var cb;
      cb = baseController.callBack(response);
      return user.saveNewUser(request.body, cb);
    },
    destroy: function(request, response) {
      var cb, id;
      cb = baseController.callBack(response);
      id = request.params.user.replace(/:/g, '');
      return user.deleteUser(id, cb);
    },
    getByEmail: function(request, response) {
      var cb, email;
      cb = baseController.callBack(response);
      email = request.params.user.replace(/:/g, '');
      return user.getUserByEmail(email, cb);
    },
    getByKnownodeId: function(request, response) {
      var cb, knownodeId;
      cb = baseController.callBack(response);
      knownodeId = request.params.user.replace(/:/g, '');
      return user.getUserByKnownodeId(knownodeId, cb);
    }
  };

}).call(this);
