// Generated by CoffeeScript 1.6.2
/*
* User: Liad Magen
* Date: 05/02/13
* Time: 12:43
*
* this is a class for managing the logins of the users in the system
*
*/


(function() {
  var Comment, userModule,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  userModule = require('./user');

  module.exports = Comment = (function(_super) {
    __extends(Comment, _super);

    function Comment(user) {
      Comment.__super__.constructor.call(this, null);
    }

    exports.autoLogin = function(user, pass, callback) {
      user - new userModule;
      return user.findOne({
        user: user
      }, function(e, o) {
        if (o) {
          return o.pass === (pass ? callback(o) : callback(null));
        } else {
          return callback(null);
        }
      });
    };

    return Comment;

  })(BaseModule);

}).call(this);
