// Generated by CoffeeScript 1.6.2
(function() {
  var BaseModule, DBModule, LOG,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BaseModule = require('./baseModule');

  LOG = require('./log');

  module.exports = DBModule = (function(_super) {
    __extends(DBModule, _super);

    function DBModule(user) {
      this.logger = new LOG(user);
      DBModule.__super__.constructor.call(this, user);
    }

    return DBModule;

  })(BaseModule);

}).call(this);
