/*** Generated by streamline 0.4.7 (callbacks) - DO NOT EDIT ***/ var __rt=require('streamline/lib/callbacks/runtime').runtime(__filename),__func=__rt.__func,__cb=__rt.__cb; (function() {











  var DBModule, KnownodeFiles, config, mongoose, postSchema, userModule, _this = this, __hasProp = {

  }.hasOwnProperty, __extends = function(child, parent) {
    for (var key in parent) { if (__hasProp.call(parent, key)) { child[key] = parent[key]; }; }; function ctor() { this.constructor = child; }; ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  userModule = require("./user");

  mongoose = require("mongoose");

  postSchema = require("../DB/PostSchema");

  config = require("../config/DB.conf");

  DBModule = require("./DBModule");

  module.exports = KnownodeFiles = (function(_super) {

    __extends(KnownodeFiles, _super);

    function KnownodeFiles(user) {
      var _this = this;
      this.deleteFile = function() {
        return KnownodeFiles.prototype.deleteFile.apply(_this, arguments); };

      this.getFile = function() {
        return KnownodeFiles.prototype.getFile.apply(_this, arguments); };

      this.saveFile = function() {
        return KnownodeFiles.prototype.saveFile.apply(_this, arguments); };

      KnownodeFiles.__super__.constructor.call(this, user);
      this.currentModule = "module/KnownodeFiles"; };


    KnownodeFiles.prototype.initDB = function(callback) {
      var db, dbURL, opts;
      this.logger.logDebug(this.currentModule, "initDB");
      opts = {
        server: {
          auto_reconnect: false,
          user: config.getDBDetails("mongoDB").user,
          pass: config.getDBDetails("mongoDB").pass } };


      dbURL = config.getDBURL("mongoDB").url;
      mongoose.connect(dbURL, opts);
      db = mongoose.connection;
      db.on("error", function(err) {
        this.logger.logError(this.currentModule, err);
        try {
          mongoose.connection.close();
          return callback(err);
        } catch (error) {
          this.logger.logError(this.currentModule, error);
          return callback(error); }; });


      return db.once("open", function() {
        var Post;
        console.log("db is open");
        Post = db.model("Post", postSchema);
        console.log("sending Post");
        return callback(null, Post); }); };



    KnownodeFiles.prototype.saveFile = function KnownodeFiles_prototype_saveFile__1(files, params, _) { var Post, opts, post, __this = this; var __frame = { name: "KnownodeFiles_prototype_saveFile__1", line: 79 }; return __func(_, this, arguments, KnownodeFiles_prototype_saveFile__1, 2, __frame, function __$KnownodeFiles_prototype_saveFile__1() {

        __this.logger.logDebug(__this.currentModule, "saveFile");
        return __this.initDB(__cb(_, __frame, 3, 13, function ___(__0, __1) { Post = __1;
          __this.logger.logDebug(__this.currentModule, "post initialized");
          post = new Post({
            fileURL: params.url,
            fileName: files.uploadedFile.name,
            abstract: params.bodyText,
            title: params.title,
            meta: {
              uploaderId: __this.user.id,
              uploaderEmail: __this.user.email,
              size: files.uploadedFile.size } });


          opts = {
            content_type: files.uploadedFile.type };

          return post.addFile(files.uploadedFile, opts, __cb(_, __frame, 19, 6, function __$KnownodeFiles_prototype_saveFile__1() {
            mongoose.connection.close();
            return _(null, post); }, true)); }, true)); }); };


    KnownodeFiles.prototype.getFile = function KnownodeFiles_prototype_getFile__2(id, _) { var Post, post, __this = this; var __frame = { name: "KnownodeFiles_prototype_getFile__2", line: 103 }; return __func(_, this, arguments, KnownodeFiles_prototype_getFile__2, 1, __frame, function __$KnownodeFiles_prototype_getFile__2() {

        __this.logger.logDebug(__this.currentModule, ("getFile " + id));
        return __this.initDB(__cb(_, __frame, 3, 13, function ___(__0, __1) { Post = __1;
          post = new Post();
          return post.getFile(id, __cb(_, __frame, 5, 13, _, true)); }, true)); }); };


    KnownodeFiles.prototype.deleteFile = function KnownodeFiles_prototype_deleteFile__3(id, _) { var Post, post, __this = this; var __frame = { name: "KnownodeFiles_prototype_deleteFile__3", line: 111 }; return __func(_, this, arguments, KnownodeFiles_prototype_deleteFile__3, 1, __frame, function __$KnownodeFiles_prototype_deleteFile__3() {

        __this.logger.logDebug(__this.currentModule, ("deleteFile " + id));
        return __this.initDB(__cb(_, __frame, 3, 13, function ___(__0, __1) { Post = __1;
          post = new Post();
          return post.deleteFile(id, __cb(_, __frame, 5, 13, _, true)); }, true)); }); };


    return KnownodeFiles;

  })(DBModule);

}).call(this);