/*** Generated by streamline 0.4.5 (callbacks) - DO NOT EDIT ***/ var __rt=require('streamline/lib/callbacks/runtime').runtime(__filename); (function() {
  var Log, __bind = function(fn, me) {
    return function() { return fn.apply(me, arguments); }; };

  module.exports = Log = (function() {

    function Log(user) {
      this.logActivity = __bind(this.logActivity, this);
      this.DB = require("../DB/LogDB");
      this.user = (user || { }); };


    Log.prototype.logActivity = function(title, description) {
      var log;
      log = new this.DB.Log;
      log.user = ((this.user && this.user.id) ? this.user.id : "anonymous");
      log.title = title;
      log.content = description;
      return log.save(console.log); };


    return Log;

  })();

}).call(this);