// Generated by CoffeeScript 1.6.2
(function() {
  var baseController, commentModule, edgeModule, knownodeModule, relationModule;

  knownodeModule = require('../../modules/knownode');

  relationModule = require('../../modules/relation');

  baseController = require('../baseController');

  commentModule = require('../../modules/comment');

  edgeModule = require('../../modules/edge');

  module.exports = {
    show: function(request, response) {
      var cb, id, modEdge;

      cb = baseController.callBack(response);
      modEdge = new edgeModule(request.user);
      id = request.params.edge.replace(/:/g, '');
      return modEdge.getRelatedNodesToEdgeId(id, cb);
    }
  };

}).call(this);
