/*** Generated by streamline 0.6.0 (callbacks) - DO NOT EDIT ***/ var __rt=require('streamline/lib/callbacks/runtime').runtime(__filename),__func=__rt.__func,__cb=__rt.__cb; (function() {
  var Connection, ConnectionDAO, Logger, Resource, User;

  Resource = require("../model/Resource");

  Connection = require("../model/Connection");

  User = require("../model/User");

  Logger = require("../log/logger");

  module.exports = ConnectionDAO = (function() {
    function ConnectionDAO() {
      this.logger = new Logger("ConnectionDAO"); };


    ConnectionDAO.prototype.create = function ConnectionDAO_prototype_create__1(data, userId, _) { var creator, endResource, startResource; var __frame = { name: "ConnectionDAO_prototype_create__1", line: 17 }; return __func(_, this, arguments, ConnectionDAO_prototype_create__1, 2, __frame, function __$ConnectionDAO_prototype_create__1() {

        return Resource.find(data.fromNodeId, __cb(_, __frame, 2, 22, function ___(__0, __1) { startResource = __1;
          return Resource.find(data.toNodeId, __cb(_, __frame, 3, 20, function ___(__0, __2) { endResource = __2;
            return User.find(userId, __cb(_, __frame, 4, 16, function ___(__0, __3) { creator = __3;
              return startResource.connectTo(endResource, creator, data, __cb(_, __frame, 5, 13, _, true)); }, true)); }, true)); }, true)); }); };


    ConnectionDAO.prototype.read = function ConnectionDAO_prototype_read__2(id, _) { var __frame = { name: "ConnectionDAO_prototype_read__2", line: 25 }; return __func(_, this, arguments, ConnectionDAO_prototype_read__2, 1, __frame, function __$ConnectionDAO_prototype_read__2() {
        return Connection.find(id, __cb(_, __frame, 1, 13, _, true)); }); };


    ConnectionDAO.prototype.update = function ConnectionDAO_prototype_update__3(id, newData, _) { var connection; var __frame = { name: "ConnectionDAO_prototype_update__3", line: 29 }; return __func(_, this, arguments, ConnectionDAO_prototype_update__3, 2, __frame, function __$ConnectionDAO_prototype_update__3() {

        return Connection.find(id, __cb(_, __frame, 2, 19, function ___(__0, __1) { connection = __1;
          return connection.update(newData, __cb(_, __frame, 3, 6, function __$ConnectionDAO_prototype_update__3() {
            return _(null, connection); }, true)); }, true)); }); };


    ConnectionDAO.prototype["delete"] = function ConnectionDAO_prototype_delete__4(id, _) { var connection; var __frame = { name: "ConnectionDAO_prototype_delete__4", line: 36 }; return __func(_, this, arguments, ConnectionDAO_prototype_delete__4, 1, __frame, function __$ConnectionDAO_prototype_delete__4() {

        return Connection.find(id, __cb(_, __frame, 2, 19, function ___(__0, __1) { connection = __1;
          return connection["delete"](__cb(_, __frame, 3, 13, _, true)); }, true)); }); };


    return ConnectionDAO;

  })();

}).call(this);