/*** Generated by streamline 0.6.0 (callbacks) - DO NOT EDIT ***/ var __rt=require('streamline/lib/callbacks/runtime').runtime(__filename),__func=__rt.__func,__cb=__rt.__cb; (function() {
  var Logger, Resource, ResourceDAO, User;

  Resource = require("../model/Resource");

  User = require("../model/User");

  Logger = require("../log/logger");

  module.exports = ResourceDAO = (function() {
    function ResourceDAO() {
      this.logger = new Logger("ResourceDAO"); };


    ResourceDAO.prototype.create = function ResourceDAO_prototype_create__1(data, userId, _) { var created, creator; var __frame = { name: "ResourceDAO_prototype_create__1", line: 15 }; return __func(_, this, arguments, ResourceDAO_prototype_create__1, 2, __frame, function __$ResourceDAO_prototype_create__1() {

        return User.find(userId, __cb(_, __frame, 2, 16, function ___(__0, __1) { creator = __1;
          return Resource.create(data, creator, __cb(_, __frame, 3, 23, function ___(__0, __3) { var __2 = created = __3; return _(null, __2); }, true)); }, true)); }); };


    ResourceDAO.prototype.read = function ResourceDAO_prototype_read__2(id, _) { var __frame = { name: "ResourceDAO_prototype_read__2", line: 21 }; return __func(_, this, arguments, ResourceDAO_prototype_read__2, 1, __frame, function __$ResourceDAO_prototype_read__2() {
        return Resource.find(id, __cb(_, __frame, 1, 13, _, true)); }); };


    ResourceDAO.prototype.update = function ResourceDAO_prototype_update__3(id, newData, _) { var resource; var __frame = { name: "ResourceDAO_prototype_update__3", line: 25 }; return __func(_, this, arguments, ResourceDAO_prototype_update__3, 2, __frame, function __$ResourceDAO_prototype_update__3() {

        return Resource.find(id, __cb(_, __frame, 2, 17, function ___(__0, __1) { resource = __1;
          return resource.update(newData, __cb(_, __frame, 3, 6, function __$ResourceDAO_prototype_update__3() {
            return _(null, resource); }, true)); }, true)); }); };


    ResourceDAO.prototype["delete"] = function ResourceDAO_prototype_delete__4(id, _) { var resource; var __frame = { name: "ResourceDAO_prototype_delete__4", line: 32 }; return __func(_, this, arguments, ResourceDAO_prototype_delete__4, 1, __frame, function __$ResourceDAO_prototype_delete__4() {

        return Resource.find(id, __cb(_, __frame, 2, 17, function ___(__0, __1) { resource = __1;
          return resource["delete"](__cb(_, __frame, 3, 13, _, true)); }, true)); }); };


    ResourceDAO.prototype.searchByKeyword = function ResourceDAO_prototype_searchByKeyword__5(query, _) { var __this = this; var __frame = { name: "ResourceDAO_prototype_searchByKeyword__5", line: 38 }; return __func(_, this, arguments, ResourceDAO_prototype_searchByKeyword__5, 1, __frame, function __$ResourceDAO_prototype_searchByKeyword__5() {
        __this.logger.debug((("searchByKeyword (query: " + query) + ")"));
        return Resource.searchByKeyword(query, __cb(_, __frame, 2, 13, _, true)); }); };


    ResourceDAO.prototype.findByUrl = function ResourceDAO_prototype_findByUrl__6(url, _) { var __this = this; var __frame = { name: "ResourceDAO_prototype_findByUrl__6", line: 43 }; return __func(_, this, arguments, ResourceDAO_prototype_findByUrl__6, 1, __frame, function __$ResourceDAO_prototype_findByUrl__6() {
        __this.logger.debug((("searchByUrl (url: " + url) + ")"));
        return Resource.findByUrl(url, __cb(_, __frame, 2, 13, _, true)); }); };


    return ResourceDAO;

  })();

}).call(this);