/*** Generated by streamline 0.6.0 (callbacks) - DO NOT EDIT ***/ var __rt=require('streamline/lib/callbacks/runtime').runtime(__filename),__func=__rt.__func,__cb=__rt.__cb,__tryCatch=__rt.__tryCatch; (function() {
  var Error, Logger, Resource, User, WikiDAO;

  Resource = require("../model/Resource");

  User = require("../model/User");

  Logger = require("../log/logger");

  Error = require("../error/Error");

  module.exports = WikiDAO = (function() {
    WikiDAO.prototype.makeWikipediaUrl = function(title) {
      return ("http://en.wikipedia.org/wiki/" + title.replace(/\ /g, "_")); };


    function WikiDAO() {
      this.logger = new Logger("WikiDAO"); };


    WikiDAO.prototype.create = function WikiDAO_prototype_create__1(data, userId, _) { var created, creator, error, url, __this = this; var __frame = { name: "WikiDAO_prototype_create__1", line: 21 }; return __func(_, this, arguments, WikiDAO_prototype_create__1, 2, __frame, function __$WikiDAO_prototype_create__1() {

        url = __this.makeWikipediaUrl(data.title); return (function ___(__then) { (function ___(_) { __tryCatch(_, function __$WikiDAO_prototype_create__1() {

              return Resource.findByUrl(url, __cb(_, __frame, 4, 15, _, true)); }); })(function ___(_error, __result) { __tryCatch(_, function __$WikiDAO_prototype_create__1() { if (_error) {

                error = _error; return (function __$WikiDAO_prototype_create__1(__then) {
                  if ((error.isCustom && (error.type === Error.Type.ENTITY_NOT_FOUND))) {
                    data.url = url;
                    data.resourceType = Resource.Type.WIKIPEDIA_ARTICLE;
                    return User.find(userId, __cb(_, __frame, 10, 20, function ___(__0, __1) { creator = __1;
                      return Resource.create(data, creator, __cb(_, __frame, 11, 27, function ___(__0, __3) { var __2 = created = __3; return _(null, __2); }, true)); }, true)); } else {

                    return _(error); } ; })(__then); } else { _(null, __result); } ; }); }); })(function ___() { __tryCatch(_, _); }); }); };




    WikiDAO.prototype.findByTitle = function WikiDAO_prototype_findByTitle__2(title, _) { var url, __this = this; var __frame = { name: "WikiDAO_prototype_findByTitle__2", line: 39 }; return __func(_, this, arguments, WikiDAO_prototype_findByTitle__2, 1, __frame, function __$WikiDAO_prototype_findByTitle__2() {

        __this.logger.debug((("findByTitle (title: " + title) + ")"));
        url = __this.makeWikipediaUrl(title);
        return Resource.findByUrl(url, __cb(_, __frame, 4, 13, _, true)); }); };


    return WikiDAO;

  })();

}).call(this);