// Generated by CoffeeScript 1.4.0

/*
* This is the routing for the users. It calls /modules/user.js for implementing its actions.
*/


(function() {
  var baseController, knownodeFileModule;

  knownodeFileModule = require('../../modules/knownodeFiles');

  baseController = require('../baseController');

  module.exports = {
    show: function(request, response) {
      var cb, id;
      cb = baseController.callBack(response);
      id = request.params.user.replace(/:/g, '');
      return knownodeFileModule.getUserByNodeId(id, cb);
    },
    create: function(request, response) {
      var cb;
      cb = baseController.callBack(response);
      return knownodeFileModule.saveFile(request.files, request.param, cb);
    }
  };

}).call(this);
