// Generated by CoffeeScript 1.6.2
/*
* This is the routing for the users. It calls /modules/user.js for implementing its actions.
*/


(function() {
  var baseController, knownodeFileModule;

  knownodeFileModule = require('../../modules/knownodeFiles');

  baseController = require('../baseController');

  module.exports = {
    show: function(request, response) {
      var fileModule, id;

      id = request.params.files.replace(/:/g, '');
      fileModule = new knownodeFileModule(request.user);
      return fileModule.sendFileToStreamHandler(response, id);
    },
    create: function(request, response) {
      var cb, fileModule;

      cb = baseController.callBack(response);
      fileModule = new knownodeFileModule(request.user);
      return fileModule.saveFile(request.files, request.param, cb);
    },
    destroy: function(request, response) {
      var cb, fileModule;

      cb = baseController.callBack(response);
      fileModule = new knownodeFileModule(request.user);
      return fileModule.deleteFile(request.files, request.param, cb);
    }
  };

}).call(this);
