// Generated by CoffeeScript 1.4.0

/*
* This is the routing for the users. It calls /modules/user.js for implementing its actions.
*/


(function() {
  var baseController, knownodeFileModule;

  knownodeFileModule = require('../../modules/knownodeFiles');

  baseController = require('../baseController');

  module.exports = {
    show: function(request, response) {
      var cb, fileModule, id;
      cb = baseController.callBack(response);
      id = request.params.files.replace(/:/g, '');
      fileModule = new knownodeFileModule(request.user);
      return fileModule.getFile(id, function(err, store) {
        var fileStream;
        if (err != null) {
          return response.json({
            error: err
          });
        } else {
          response.writeHead(200, {
            'Content-Type': store.contentType,
            'Content-Length': store.length,
            'Content-disposition': 'attachment; filename=' + store.filename
          });
          fileStream = store.stream(false);
          fileStream.pipe(response, {
            end: false
          });
          return fileStream.on("end", function() {
            return fileStream.end();
          });
        }
      });
    },
    create: function(request, response) {
      var cb, fileModule;
      cb = baseController.callBack(response);
      fileModule = new knownodeFileModule(request.user);
      return fileModule.saveFile(request.files, request.param, cb);
    },
    destroy: function(request, response) {
      var cb, fileModule;
      cb = baseController.callBack(response);
      fileModule = new knownodeFileModule(request.user);
      return fileModule.deleteFile(request.files, request.param, cb);
    }
  };

}).call(this);
