// Generated by CoffeeScript 1.6.1
(function() {
  var ConnectionValidator, NodeValidator,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  NodeValidator = require('./nodeValidator');

  module.exports = ConnectionValidator = (function(_super) {

    __extends(ConnectionValidator, _super);

    function ConnectionValidator() {
      ConnectionValidator.__super__.constructor.call(this, 'kn_Edge');
    }

    ConnectionValidator.prototype.validate = function(data, _) {
      console.log(data);
      ConnectionValidator.__super__.validate.call(this, data);
      this.check(data.__CreatedOn__).notNull().isInt();
      this.check(data.title).notEmpty();
      this.check(data.bodyText).notEmpty();
      this.check(data.connectionType).notEmpty();
      this.check(data.fromNodeId).notEmpty();
      this.check(data.toNodeId).notEmpty();
      return data.active = this.sanitize(data.active).toBoolean();
    };

    return ConnectionValidator;

  })(NodeValidator);

}).call(this);
