// Generated by CoffeeScript 1.6.1
(function() {
  var NodeValidator, Validator;

  Validator = require('validator');

  module.exports = NodeValidator = (function() {

    function NodeValidator(nodeType) {
      this.nodeType = nodeType;
      this.check = Validator.check;
      this.sanitize = Validator.sanitize;
    }

    NodeValidator.prototype.validate = function(data, _) {
      this.check(data.KN_ID).notEmpty();
      return this.check(data.nodeType).notNull().equals(this.nodeType);
    };

    return NodeValidator;

  })();

}).call(this);
